# Generate a random password for the RDS master user
resource "random_password" "db_password" {
  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# Random suffix to avoid recovery-wait conflicts when destroy→apply cycles reuse the same secret name
resource "random_id" "db_secret_suffix" {
  byte_length = 4
}

# Secrets Manager secret (container)
resource "aws_secretsmanager_secret" "db_password" {
  name                    = "membership-blog-eks-db-password-${random_id.db_secret_suffix.hex}"
  description             = "RDS master password auto-generated by Terraform"
  recovery_window_in_days = 0
}

# Store the password in Secrets Manager
resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db_password.result
}

# DB subnet group
resource "aws_db_subnet_group" "main" {
  name       = "membership-blog-eks-db-subnet-group"
  subnet_ids = var.private_subnet_ids

  tags = { Name = "membership-blog-eks-db-subnet-group" }
}

# Security group: allow inbound PostgreSQL only from within the VPC
resource "aws_security_group" "db" {
  name   = "membership-blog-eks-db-sg"
  vpc_id = var.vpc_id

  ingress {
    from_port   = 5432
    to_port     = 5432
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/16"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

# RDS instance
resource "aws_db_instance" "main" {
  identifier             = "membership-blog-eks-db"
  engine                 = "postgres"
  engine_version         = "15"
  instance_class         = "db.t3.micro" # free tier eligible
  allocated_storage      = 20            # free tier limit: 20 GB
  db_name                = "membership_db"
  username               = "postgres"
  password               = random_password.db_password.result
  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.db.id]
  skip_final_snapshot    = true
  publicly_accessible    = false
}
