apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: membership-blog-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/${{ github.repository_owner }}/membership-site-on-eks.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
